/**
 * Glosario de términos — PPS Academy
 * Cubre todos los conceptos del programa de 6 módulos
 */
export const glossaryTerms: { term: string; definition: string; category?: string }[] = [
  // ── Fundamentos ────────────────────────────────────────────
  { term: 'Ciberseguridad', category: 'Fundamentos',
    definition: 'Disciplina que protege activos digitales (información, hardware, software y redes) frente a ataques, accesos no autorizados y daños.' },
  { term: 'OWASP Top Ten', category: 'Fundamentos',
    definition: 'Lista de las 10 vulnerabilidades más críticas en aplicaciones web, publicada y actualizada por OWASP. Referente mundial en seguridad web.' },
  { term: 'Superficie de ataque', category: 'Fundamentos',
    definition: 'Conjunto de puntos de entrada potenciales a través de los cuales un atacante puede intentar ganar acceso a un sistema.' },
  { term: 'Vector de ataque', category: 'Fundamentos',
    definition: 'Método o ruta que un atacante usa para acceder ilegalmente a un sistema, como explotar una vulnerabilidad web o de red.' },
  { term: 'Vulnerabilidad', category: 'Fundamentos',
    definition: 'Debilidad en un sistema, aplicación o proceso que puede ser explotada para comprometer su integridad, confidencialidad o disponibilidad.' },
  { term: 'Exploit', category: 'Fundamentos',
    definition: 'Código o técnica que aprovecha una vulnerabilidad para causar un comportamiento no deseado en un sistema.' },
  { term: 'Payload', category: 'Fundamentos',
    definition: 'En seguridad ofensiva, la parte del exploit que ejecuta la acción maliciosa (shellcode, reverse shell, JavaScript inyectado, etc.).' },
  { term: 'Pentesting', category: 'Fundamentos',
    definition: 'Prueba de penetración: simulación controlada de ataques para identificar vulnerabilidades antes que actores maliciosos.' },
  { term: 'Red Team', category: 'Fundamentos',
    definition: 'Equipo de seguridad que simula ataques reales contra una organización para evaluar sus capacidades defensivas.' },
  { term: 'Blue Team', category: 'Fundamentos',
    definition: 'Equipo de seguridad encargado de la defensa, monitorización y respuesta a incidentes en una organización.' },
  { term: 'Zero-day (0-day)', category: 'Fundamentos',
    definition: 'Vulnerabilidad desconocida para el fabricante, para la que no existe parche disponible en el momento de ser explotada.' },
  { term: 'CVE', category: 'Fundamentos',
    definition: 'Common Vulnerabilities and Exposures: sistema de identificación única para vulnerabilidades de seguridad conocidas públicamente.' },
  { term: 'CVSS', category: 'Fundamentos',
    definition: 'Common Vulnerability Scoring System: sistema de puntuación numérica para evaluar la severidad de vulnerabilidades (0-10).' },

  // ── Vulnerabilidades de entrada ────────────────────────────
  { term: 'SQL Injection', category: 'Inyección',
    definition: 'Vulnerabilidad que permite inyectar código SQL malicioso en consultas a la base de datos, pudiendo extraer, modificar o eliminar datos.' },
  { term: 'XSS', category: 'Inyección',
    definition: 'Cross-Site Scripting: inyección de scripts maliciosos en páginas web que se ejecutan en el navegador de otras víctimas.' },
  { term: 'XSS reflejado', category: 'Inyección',
    definition: 'Variante de XSS en la que el payload se refleja inmediatamente en la respuesta HTTP, generalmente a través de un parámetro de URL.' },
  { term: 'XSS almacenado', category: 'Inyección',
    definition: 'Variante de XSS en la que el payload se persiste en la base de datos y se ejecuta cada vez que la página es cargada por cualquier usuario.' },
  { term: 'XSS basado en DOM', category: 'Inyección',
    definition: 'Variante de XSS donde la vulnerabilidad reside en código JavaScript del lado cliente que modifica el DOM sin saneamiento previo.' },
  { term: 'CSRF', category: 'Inyección',
    definition: 'Cross-Site Request Forgery: engaña al navegador autenticado de la víctima para ejecutar acciones no autorizadas en su nombre.' },
  { term: 'RCE', category: 'Inyección',
    definition: 'Remote Code Execution: ejecución remota de código en el servidor, habitualmente mediante command injection o deserialización insegura.' },
  { term: 'Command Injection', category: 'Inyección',
    definition: 'Vulnerabilidad que permite inyectar y ejecutar comandos del sistema operativo a través de campos de entrada no saneados.' },
  { term: 'SSRF', category: 'Inyección',
    definition: 'Server-Side Request Forgery: fuerza al servidor a realizar peticiones HTTP a recursos internos o externos arbitrarios.' },
  { term: 'XXE', category: 'Inyección',
    definition: 'XML External Entity: explotación de un parser XML inseguro que procesa entidades externas, permitiendo lectura de archivos o SSRF.' },
  { term: 'LFI', category: 'Inyección',
    definition: 'Local File Inclusion: inclusión de archivos locales del servidor mediante parámetros de entrada no validados.' },
  { term: 'RFI', category: 'Inyección',
    definition: 'Remote File Inclusion: inclusión de archivos desde servidores externos mediante parámetros de entrada, pudiendo ejecutar código remoto.' },
  { term: 'Path Traversal', category: 'Inyección',
    definition: 'Técnica de inyección que usa secuencias ../ para acceder a ficheros fuera del directorio web raíz.' },
  { term: 'IDOR', category: 'Inyección',
    definition: 'Insecure Direct Object Reference: acceso a recursos de otros usuarios modificando referencias directas (IDs) sin validar la autorización.' },
  { term: 'SSTI', category: 'Inyección',
    definition: 'Server-Side Template Injection: inyección en motores de plantillas (Jinja2, Twig) que puede llevar a RCE.' },
  { term: 'Open Redirect', category: 'Inyección',
    definition: 'Vulnerabilidad que permite redirigir a usuarios hacia URLs arbitrarias externas, usada en phishing.' },

  // ── Autenticación y sesiones ───────────────────────────────
  { term: 'Broken Authentication', category: 'Autenticación',
    definition: 'Vulnerabilidades en mecanismos de autenticación como contraseñas débiles, sesiones no caducadas o falta de MFA.' },
  { term: 'JWT', category: 'Autenticación',
    definition: 'JSON Web Token: estándar RFC 7519 para transmitir claims firmados (y opcionalmente cifrados) entre partes.' },
  { term: 'OAuth 2.0', category: 'Autenticación',
    definition: 'Protocolo de autorización estándar que permite a aplicaciones obtener acceso limitado a cuentas de usuario.' },
  { term: 'Session Fixation', category: 'Autenticación',
    definition: 'Ataque donde el adversario fija el ID de sesión de la víctima antes de que se autentique para secuestrar su sesión.' },
  { term: 'Session Hijacking', category: 'Autenticación',
    definition: 'Robo del ID de sesión de un usuario para suplantar su identidad sin necesitar credenciales.' },
  { term: 'Brute Force', category: 'Autenticación',
    definition: 'Ataque que prueba sistemáticamente contraseñas o claves hasta encontrar la correcta.' },
  { term: 'Credential Stuffing', category: 'Autenticación',
    definition: 'Uso automatizado de credenciales filtradas de otros sitios para intentar acceder a cuentas que reutilizan contraseñas.' },
  { term: 'MFA', category: 'Autenticación',
    definition: 'Multi-Factor Authentication: autenticación que requiere dos o más factores independientes (conocimiento, posesión, biometría).' },

  // ── Protección de datos ────────────────────────────────────
  { term: 'TLS', category: 'Cifrado',
    definition: 'Transport Layer Security: protocolo criptográfico que garantiza confidencialidad e integridad en comunicaciones de red (sucesor de SSL).' },
  { term: 'AES', category: 'Cifrado',
    definition: 'Advanced Encryption Standard: algoritmo de cifrado simétrico por bloques ampliamente usado (128/192/256 bits).' },
  { term: 'RBAC', category: 'Control de acceso',
    definition: 'Role-Based Access Control: modelo de control de acceso donde los permisos se asignan a roles y los roles a usuarios.' },
  { term: 'ABAC', category: 'Control de acceso',
    definition: 'Attribute-Based Access Control: modelo de control de acceso donde las decisiones se toman en función de atributos del usuario, recurso y contexto.' },
  { term: 'Principio de mínimo privilegio', category: 'Control de acceso',
    definition: 'Principio de seguridad que establece que un usuario o proceso solo debe tener los permisos estrictamente necesarios para su función.' },
  { term: 'Hashing', category: 'Cifrado',
    definition: 'Función matemática unidireccional que transforma datos en un resumen de longitud fija. En contraseñas se usan bcrypt, argon2 o PBKDF2.' },
  { term: 'Salt', category: 'Cifrado',
    definition: 'Valor aleatorio añadido a una contraseña antes de hashearla para evitar ataques de diccionario y rainbow tables.' },

  // ── Configuración segura ───────────────────────────────────
  { term: 'CSP', category: 'Headers',
    definition: 'Content Security Policy: cabecera HTTP que define fuentes permitidas de contenido (scripts, estilos, imágenes). Mitiga XSS.' },
  { term: 'HSTS', category: 'Headers',
    definition: 'HTTP Strict Transport Security: cabecera que fuerza al navegador a usar siempre HTTPS. Protege contra SSL stripping.' },
  { term: 'CORS', category: 'Headers',
    definition: 'Cross-Origin Resource Sharing: mecanismo que controla qué orígenes externos pueden acceder a recursos de un servidor.' },
  { term: 'Clickjacking', category: 'Headers',
    definition: 'Ataque que superpone un iframe invisible sobre contenido legítimo para engañar al usuario a hacer clic en acciones no deseadas. Mitigado con X-Frame-Options.' },
  { term: 'Misconfiguration', category: 'Configuración',
    definition: 'Configuración incorrecta o por defecto en servidores, bases de datos o aplicaciones que genera exposición a vulnerabilidades.' },
  { term: 'Security Headers', category: 'Configuración',
    definition: 'Conjunto de cabeceras HTTP (CSP, HSTS, X-Frame-Options, etc.) que refuerzan la seguridad del navegador frente a ataques comunes.' },

  // ── DevSecOps y herramientas ───────────────────────────────
  { term: 'SAST', category: 'DevSecOps',
    definition: 'Static Application Security Testing: análisis estático del código fuente para detectar vulnerabilidades sin ejecutar la aplicación.' },
  { term: 'DAST', category: 'DevSecOps',
    definition: 'Dynamic Application Security Testing: análisis de seguridad de una aplicación en ejecución mediante peticiones HTTP automatizadas.' },
  { term: 'SCA', category: 'DevSecOps',
    definition: 'Software Composition Analysis: análisis de dependencias de terceros para detectar versiones vulnerables o con licencias problemáticas.' },
  { term: 'DevSecOps', category: 'DevSecOps',
    definition: 'Práctica que integra seguridad en cada fase del ciclo de desarrollo (desarrollo, CI/CD, producción) en lugar de añadirla al final.' },
  { term: 'WAF', category: 'Defensa',
    definition: 'Web Application Firewall: dispositivo o software que filtra, monitoriza y bloquea tráfico HTTP malicioso antes de que llegue a la aplicación.' },

  // ── Normativa ──────────────────────────────────────────────
  { term: 'RGPD', category: 'Normativa',
    definition: 'Reglamento General de Protección de Datos: legislación europea que regula el tratamiento de datos personales.' },
  { term: 'LOPD', category: 'Normativa',
    definition: 'Ley Orgánica de Protección de Datos: legislación española de protección de datos personales, adaptación nacional del RGPD.' },
  { term: 'ISO 27001', category: 'Normativa',
    definition: 'Estándar internacional para sistemas de gestión de la seguridad de la información (SGSI).' },
  { term: 'ENS', category: 'Normativa',
    definition: 'Esquema Nacional de Seguridad: marco normativo español para garantizar la seguridad de los sistemas de información de las AAPP.' },
]
